name = "Snakes"
uuid = "b925447e-1385-4aec-88e4-0f762718f6ef"
authors = ["roboneet <neethumariyajoy@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
